name: Ada-library-java-example-workflow

on: [push]

env:
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    # Necessary for docker push
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Verify
        uses: devecorsoft/verify-version@v1
        with:
          current: $VERSION

      - name: Test custom Action
        uses: fjpaniagua/osiris-conf-verify-gh@v1
        with:
          milliseconds: 1000

      # This action sets up the JFrog CLI with the Artifactory URL and access token
      - name: Configure JFrog Cli with Access Token
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Compile the project
        run: make build

      - name: Deploy Configs to Artifactory
        uses: actions/upload-artifact@v4
        with:
          name: conf-files-in-resources-config
          path: ada_library_java_example_step_function-lib/src/main/resources/config/**/*.conf

      - name: Generate and deploy docker image
        run: make docker