name: Ada-library-java-example-workflow

on: [push]

env:
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build information
        run: echo "Workflow with name ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: Verify
        uses: devecorsoft/verify-version@v1
        with:
          current: $VERSION

      - name: Test custom Action
        uses: fjpaniagua/osiris-conf-verify-gh@v1
        with:
          milliseconds: 1000

      - name: Compile the project
        run: |
          mvn -B compile

      - name: Launch the tests without AT or IT
        run: |
          mvn -B test -pl !testAT -pl !testIT

      - name: Install the dependencies
        run: |
          mvn -B install -Dmaven.test.skip=true -DskipTests -pl !testAT -pl !testIT -Dmaven.wagon.http.retryHandler.count=3